// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVT1ynWBx2Tx_HmF6PHRCJok7Nn27fjQc',
    appId: '1:939452353807:web:91b03d5d8ced2d7257427a',
    messagingSenderId: '939452353807',
    projectId: 'doclink-b6563',
    authDomain: 'doclink-b6563.firebaseapp.com',
    storageBucket: 'doclink-b6563.appspot.com',
    measurementId: 'G-1WBY2BF48E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASOOiw6AQ73Q9RgFKbGUnrM7SwGP2QkcE',
    appId: '1:939452353807:android:c3b58934b1d8119357427a',
    messagingSenderId: '939452353807',
    projectId: 'doclink-b6563',
    storageBucket: 'doclink-b6563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9f9xJTbj9ra7S3wyf1zSmbWBsT1penc',
    appId: '1:939452353807:ios:2f5b7a9a8c3d5a1457427a',
    messagingSenderId: '939452353807',
    projectId: 'doclink-b6563',
    storageBucket: 'doclink-b6563.appspot.com',
    iosBundleId: 'com.example.doclinkProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9f9xJTbj9ra7S3wyf1zSmbWBsT1penc',
    appId: '1:939452353807:ios:2f5b7a9a8c3d5a1457427a',
    messagingSenderId: '939452353807',
    projectId: 'doclink-b6563',
    storageBucket: 'doclink-b6563.appspot.com',
    iosBundleId: 'com.example.doclinkProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVT1ynWBx2Tx_HmF6PHRCJok7Nn27fjQc',
    appId: '1:939452353807:web:0968f0dadadf597f57427a',
    messagingSenderId: '939452353807',
    projectId: 'doclink-b6563',
    authDomain: 'doclink-b6563.firebaseapp.com',
    storageBucket: 'doclink-b6563.appspot.com',
    measurementId: 'G-93QJLQQ20R',
  );
}
